name: Build and Deploy
push:
  branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACTION_SECRET }}
          TARGET_REPO: kllmllmn/vuepress-play
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist
          # CNAME: https://www.xxx.com
